service: hive-notes
image: thomassloboda/hive-notes
servers:
  web:
    - 91.214.190.160
registry:
  username: thomassloboda
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
  args:
    NPM_TOKEN: ${NPM_TOKEN}
env:
  clear:
    HOST: 0.0.0.0
    PORT: 4000
proxy:
  healthcheck:
    path: /
ssh:
  user: debian
  config: true
  log_level: debug
